/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package car_sales;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.util.List;


/**
 *
 * @author adria
 */
import java.awt.image.BufferedImage;
import static java.lang.Math.min;
public final class delCarPanel extends javax.swing.JPanel {

    private List<Car> vect;
    private int pagenr = 0;
    private int pagemax;
    
    
    public void load_page(){
        
        MainPanel.setLayout(new BoxLayout(MainPanel, BoxLayout.Y_AXIS));

        for (int i = 5 * pagenr; i < Math.min(5 * (pagenr + 1), vect.size()); i++) {
            // Panoul pentru fiecare mașină
            JPanel carPanel = new JPanel();
            carPanel.setLayout(new BorderLayout());
            carPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY)); // Border pentru delimitare
            carPanel.setPreferredSize(new Dimension(800, 120)); // Dimensiune fixă a fiecărui panou

            // Crearea JLabel pentru imaginea mașinii
            JLabel carImage = new JLabel();
            carImage.setPreferredSize(new Dimension(280, 150));
            carImage.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Border pentru imagine

            if (!vect.get(i).getImages().isEmpty()) {
                BufferedImage originalImage = vect.get(i).getImages().get(0); // Prima imagine
                Image scaledImage = originalImage.getScaledInstance(280, 150, Image.SCALE_SMOOTH); // Scalare
                ImageIcon carImageIcon = new ImageIcon(scaledImage);

                carImage.setIcon(carImageIcon);
                carImage.setHorizontalAlignment(JLabel.CENTER); // Centrare pe orizontală
                carImage.setVerticalAlignment(JLabel.CENTER);   // Centrare pe verticală
            }

            // Crearea JLabel pentru detalii despre mașină
            JLabel carDetails = new JLabel("<html><b>" + vect.get(i).getName() + " " + vect.get(i).getModel() + "</b><br><br>"
                    + "Preț: " + vect.get(i).getPrice() + "<br><br>"
                    + "Km: " + vect.get(i).getKilometers() + "");
            carDetails.setVerticalAlignment(SwingConstants.CENTER);
            carDetails.setFont(new Font("Arial", Font.PLAIN, 20));

            // Panoul pentru butonul de ștergere
            JPanel deletePanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            deletePanel.setPreferredSize(new Dimension(100, 120)); // Dimensiune fixă
            JButton deleteButton = new JButton("Delete");
            deleteButton.setBackground(Color.RED);
            deleteButton.setForeground(Color.WHITE);

            // Acțiunea butonului de ștergere
            final int carIndex = i;
            deleteButton.addActionListener(e -> {
                vect.remove(carIndex); // Șterge mașina din vector
                MainPanel.remove(carPanel); // Șterge panoul din UI
                MainPanel.revalidate(); // Revalidare layout
                MainPanel.repaint(); // Repictare UI
            });

            deletePanel.add(deleteButton);

            // Adăugarea componentelor în JPanel
            carPanel.add(carImage, BorderLayout.WEST);  // Imaginea în stânga
            carPanel.add(carDetails, BorderLayout.CENTER); // Detalii în centru
            carPanel.add(deletePanel, BorderLayout.EAST);  // Butonul de ștergere în dreapta

            // Click pe panoul mașinii pentru detalii
  
            MainPanel.add(carPanel); // Adăugăm panelul în MainPanel
        }

        // Revalidăm și repictăm panoul pentru a afișa noile componente
        MainPanel.revalidate();
        MainPanel.repaint();
        }
    
    public delCarPanel(int pagenr,List<Car> vect) {
        
        this.pagenr = pagenr;
        this.vect = vect;
        this.pagemax = vect.size() / 5 + 1;
        initComponents();
        
        load_page();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jLabelPageNumber = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jLabelPageNumber.setText("Page : " + 1);

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButtonBack)
                .addGap(245, 245, 245)
                .addComponent(jLabelPageNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNext)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBack)
                        .addComponent(jLabelPageNumber)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        if(pagenr - 1 >= 0){
            pagenr--;
            MainPanel.removeAll();
            jLabelPageNumber.setText("<html><b>" + "Page : " + "<html><b>" + (pagenr + 1));
            load_page();
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        if(pagenr + 1 < pagemax){
            pagenr++;
            MainPanel.removeAll();
            jLabelPageNumber.setText("<html><b>" + "Page : " + "<html><b>" + (pagenr + 1));
            load_page();
        }
    }//GEN-LAST:event_jButtonNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabelPageNumber;
    // End of variables declaration//GEN-END:variables
}
