/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_sales;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;

/**
 *
 * @author adria
 */
public class Main_Board extends javax.swing.JFrame {

    private static User user;
    private int pagenr = 0;
    //private int pagemax = 
    
    /**
     * Creates new form Main_Board
     * @param user
     */
    public Main_Board(User user){
        this.user = user;
        
        initComponents();
        
        load_page();
        
    }
    
    public void load_page(){
        
        MainPanel.setLayout(new BoxLayout(MainPanel, BoxLayout.Y_AXIS));

        for(int i = 5 * pagenr + 1 ; i <= 5 * (pagenr + 1); i++){
            System.out.println(pagenr);
            // Panoul pentru fiecare mașină
            JPanel carPanel = new JPanel();
            carPanel.setLayout(new BorderLayout());
            carPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY)); // Border pentru delimitare
            carPanel.setPreferredSize(new Dimension(800, 120)); // Dimensiune fixă a fiecărui panou

            JLabel carImage = new JLabel("Imagine Mașină " + i, JLabel.CENTER);
            carImage.setPreferredSize(new Dimension(100, 100));
            carImage.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Border pentru imagine

         
            JLabel carDetails = new JLabel("<html><b>Mitsubishi Lancer EVO X</b><br>Preț: 34.990€<br>Km: 44.100</html>");
            carDetails.setVerticalAlignment(SwingConstants.CENTER);

            carPanel.add(carImage, BorderLayout.WEST);  // Imaginea în stânga
            carPanel.add(carDetails, BorderLayout.CENTER); // Detalii în centru

            // Adăugăm carPanel în MainPanel
            MainPanel.add(carPanel);

           
        }

        // Revalidăm și repictăm panoul pentru a afișa noile componente
        MainPanel.revalidate();
        MainPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register_MainMenu = new javax.swing.JButton();
        Register_MainMenu1 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jButtonContact = new javax.swing.JButton();
        jButtonAddCar = new javax.swing.JButton();
        jButtonDelCar = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        Main_Button_LogOut1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        Register_MainMenu.setBackground(new java.awt.Color(153, 153, 255));
        Register_MainMenu.setText("Main Menu");
        Register_MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_MainMenuActionPerformed(evt);
            }
        });

        Register_MainMenu1.setBackground(new java.awt.Color(153, 153, 255));
        Register_MainMenu1.setText("Main Menu");
        Register_MainMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_MainMenu1ActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 950, 640));

        jButtonContact.setFocusPainted(false);
        jButtonContact.setBorderPainted(false);
        jButtonContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonContact.setText("Contact");
        jButtonContact.setBorderPainted(false);
        jButtonContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContactMouseExited(evt);
            }
        });
        jButtonContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContactActionPerformed(evt);
            }
        });

        if(user.isAdmin() == false){
            jButtonAddCar.setVisible(false);
        }
        jButtonAddCar.setText("Add Car");
        jButtonAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCarActionPerformed(evt);
            }
        });

        if(user.isAdmin() == false){
            jButtonDelCar.setVisible(false);
        }
        jButtonDelCar.setText("Del Car");
        jButtonDelCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDelCarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDelCarMouseExited(evt);
            }
        });
        jButtonDelCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelCarActionPerformed(evt);
            }
        });

        jButtonHome.setFocusPainted(false);      // Elimină border-ul de focus
        jButtonHome.setBorderPainted(false);
        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.setBorderPainted(false);
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseExited(evt);
            }
        });
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        Main_Button_LogOut1.setBackground(new java.awt.Color(242, 242, 242));
        Main_Button_LogOut1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Main_Button_LogOut1.setText("Log out");
        Main_Button_LogOut1.setBorderPainted(false);
        Main_Button_LogOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main_Button_LogOut1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main_Button_LogOut1MouseExited(evt);
            }
        });
        Main_Button_LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Button_LogOut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonDelCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(Main_Button_LogOut1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jButtonAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDelCar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonContact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(Main_Button_LogOut1))
        );

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 670));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, -1, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Register_MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_MainMenuActionPerformed
        Home_Page Home_Page = new Home_Page();
        Home_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Register_MainMenuActionPerformed

    private void Register_MainMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_MainMenu1ActionPerformed
        Home_Page Home_Page = new Home_Page();
        Home_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Register_MainMenu1ActionPerformed

    private void jButtonAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonAddCarActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseEntered
        // TODO add your handling code here:
        jButtonHome.setBackground(Color.gray);
    }//GEN-LAST:event_jButtonHomeMouseEntered

    private void jButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseExited
        // TODO add your handling code here;
        jButtonHome.setBackground(new java.awt.Color(242, 242, 242));
    }//GEN-LAST:event_jButtonHomeMouseExited

    private void jButtonContactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContactMouseEntered
        jButtonContact.setBackground(Color.gray);
    }//GEN-LAST:event_jButtonContactMouseEntered

    private void jButtonContactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContactMouseExited
        jButtonContact.setBackground(new java.awt.Color(242, 242, 242));
    }//GEN-LAST:event_jButtonContactMouseExited

    private void jButtonContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContactActionPerformed
        
    }//GEN-LAST:event_jButtonContactActionPerformed

    private void jButtonDelCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelCarActionPerformed

    private void Main_Button_LogOut1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_Button_LogOut1MouseEntered
       Main_Button_LogOut1.setBackground(Color.gray);
    }//GEN-LAST:event_Main_Button_LogOut1MouseEntered

    private void Main_Button_LogOut1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_Button_LogOut1MouseExited
        Main_Button_LogOut1.setBackground(new java.awt.Color(242, 242, 242));
    }//GEN-LAST:event_Main_Button_LogOut1MouseExited

    private void Main_Button_LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Button_LogOut1ActionPerformed
        Home_Page Home_Page = new Home_Page();
        Home_Page.setVisible(true);
        user = null;
        this.dispose();
    }//GEN-LAST:event_Main_Button_LogOut1ActionPerformed

    private void jButtonDelCarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelCarMouseEntered
        jButtonDelCar.setBackground(Color.gray);
    }//GEN-LAST:event_jButtonDelCarMouseEntered

    private void jButtonDelCarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelCarMouseExited
        jButtonDelCar.setBackground(new java.awt.Color(242, 242, 242));
    }//GEN-LAST:event_jButtonDelCarMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(pagenr + 1 <= 5){
            pagenr++;
            MainPanel.removeAll();
            load_page();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(pagenr - 1 >= 0){
            pagenr--;
            MainPanel.removeAll();
            load_page();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Board(user).setVisible(true);
            }
        });
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Main_Button_LogOut1;
    private javax.swing.JButton Register_MainMenu;
    private javax.swing.JButton Register_MainMenu1;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddCar;
    private javax.swing.JButton jButtonContact;
    private javax.swing.JButton jButtonDelCar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
